name: Mirror bot

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge upstream branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

          git remote add upstream https://github.com/tgstation/tgstation.git
          git fetch upstream master

          # git checkout -b update
          git merge upstream/master
        continue-on-error: true
      - name: Print merge conflicts
        id: merge-conflicts
        run: |
          git diff --name-only --diff-filter=U
      - name: Commit with conflicts
        run: |
          git commit --all --no-edit
      # git push -u origin update --force
      # Create a pull request
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          base: master
          branch: update
          delete-branch: true
          title: 'TG Update'
          body: 'This is an automated pull request to merge the latest changes from upstream repository'
