name: Mirror bot

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  pr_title: TG Update
  pr_body: This is an automated pull request to merge the latest changes from upstream repository. See last commit's description for conflicts.
  pr_branch: update
  remote_url: https://github.com/tgstation/tgstation.git
  remote_branch: master
  commiter_name: github-actions[bot]
  commiter_email: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add upstream remote
        run: |
          git config user.name "$commiter_name"
          git config user.email "$commiter_email"

          git remote add upstream "$remote_url"
          git fetch upstream $remote_branch
      - name: Merge upstream branch
        run: |
          git merge upstream/$remote_branch
        continue-on-error: true
      - name: Print conflicts
        run: |
          git diff --name-only --diff-filter=U
      - name: Commit with conflicts
        run: |
          git commit --all --no-edit
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ env.commiter_name }} <${{ env.commiter_email }}>
          branch: ${{ env.pr_branch }}
          branch-suffix: short-commit-hash
          delete-branch: true
          title: ${{ env.pr_title }}
          body: ${{ env.pr_body }}
